name: Build and Pre-Release Rojo Project

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Install pesde from release
        run: |
          P_VERSION="0.6.2"
          ASSET="pesde-${P_VERSION}-linux-x86_64.zip"
          curl -L -o pesde.zip "https://github.com/pesde-pkg/pesde/releases/download/v${P_VERSION}/${ASSET}"
          unzip pesde.zip -d pesde-bin
          chmod +x pesde-bin/pesde
          echo "$GITHUB_WORKSPACE/pesde-bin" >> $GITHUB_PATH


      - name: 📦 Install toolchain with pesde
        run: |
          pesde self-install
          pesde install

      - name: 🟡 Run blink main
        run: blink main

      - name: 🔨 Build Rojo project
        run: rojo build --output build.rbxlx

      - name: 🛠️ Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: 🔐 Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: 🚀 Create Pre-release with build.rbxlx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="auto-${{ github.sha }}"
          TITLE="Auto Build: $TAG"
          NOTES="Automated pre-release for commit ${{ github.sha }}"

          gh release create "$TAG" build.rbxlx \
            --title "$TITLE" \
            --notes "$NOTES" \
            --prerelease
