name: Build Pre-release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Pesde
        uses: lumin-org/setup-pesde@v0.4.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
 
      - name: Prebuild
        run: |
          set -euo pipefail
          export PATH="$PATH:$HOME/.pesde/bin"
          pesde install
          mkdir -p src/network
          blink main || { echo "Error: Prebuild failed"; exit 1; }

      - name: Build
        run: |
          set -euo pipefail
          export PATH="$PATH:$HOME/.pesde/bin"
          rojo build --output rcs.rbxlx || { echo "Error: Build failed"; exit 1; }

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.sha }}
          name: Auto Build ${{ github.sha }}
          body: Automated build for commit ${{ github.sha }}
          prerelease: true
          files: rcs.rbxlx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          rm -rf pesde-bin rcs.rbxlx
