name: Build & Release Roblox Place

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v1.2.3)'
        required: true
      prerelease:
        description: 'Is this a pre-release? (true/false)'
        required: true
        default: 'true'
      description:
        description: 'Release description'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rokit
        run:
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash

      - name: Install Dependencies
        run: |
          rokit install -g rojo
          rokit install -g blink

      - name: Prebuild steps
        run: |
          blink main

      - name: Compile Roblox Place
        run: |
          rojo build -o build/${{ github.event.inputs.version }}.rbxl

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          prerelease: ${{ github.event.inputs.prerelease }}
          files: build/Place.rbxl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
